{% set name = "cuda-nvtx" %}
{% set version = "12.2.140" %}
{% set cuda_version = "12.2" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "ppc64le-linux" %}  # [ppc64le]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set target_name = "x64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_nvtx/{{ platform }}/cuda_nvtx-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 2651bfb5c15fc546556da2d6b1dc48c97e1ee6f8c38d3f1910df56f24d5d028e  # [linux64]
  sha256: 5e41c750f1677801848765b0db6ac1672b2ea29cc2f5c0ef914d84e52e2a4989  # [ppc64le]
  sha256: b94ecd3824a7ecaf95b3d74b8972a29aae5ab98af349333f9c737f106d10b16a  # [aarch64]
  sha256: 6e68b436760aa05a5190d04c104a2c4f2f47073b099c6c25cb989a769c69f77a  # [win]

build:
  number: 0
  skip: true  # [osx]
  binary_relocation: false

test:
  requires:
    - patchelf  # [linux]
  files:
    - test-rpath.sh
  commands:
    - test -L $PREFIX/lib/libnvToolsExt.so.1                                # [linux]
    - test -L $PREFIX/lib/libnvToolsExt.so.1.0.0                            # [linux]
    - test -L $PREFIX/targets/{{ target_name }}/lib/libnvToolsExt.so.1      # [linux]
    - test -f $PREFIX/targets/{{ target_name }}/lib/libnvToolsExt.so.1.0.0  # [linux]
    - bash test-rpath.sh                                                    # [linux]

outputs:
  - name: cuda-nvtx
    build:
        skip: true  # [not linux]
    files:
      - lib/libnv*.so.*                       # [linux]
      - targets/{{ target_name }}/lib/*.so.*  # [linux]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
        - patchelf <0.18.0  # [linux]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    # Tests are defined at the top level, due to package/output name conflicts.
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: A C-based API for annotating events, code ranges, and resources
      description: |
        A C-based API for annotating events, code ranges, and resources in your
        applications. Applications which integrate NVTX can use the Visual Profiler
        to capture and visualize these events and ranges.
      doc_url: https://docs.nvidia.com/nvtx/

  - name: cuda-nvtx-dev
    build:
      run_exports:                                        # [linux]
        - {{ pin_subpackage("cuda-nvtx", max_pin='x') }}  # [linux]
    files:
      - lib/libnv*.so                                    # [linux]
      - lib/pkgconfig                                    # [linux]
      - targets/{{ target_name }}/lib/*.so               # [linux]
      - targets/{{ target_name }}/include/nvToolsExt*.h  # [linux]
      - targets/{{ target_name }}/include/nvtx3          # [linux]
      - Library\include\targets\{{ target_name }}        # [win]
    requirements:
      build:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
      host:
        - cuda-version {{ cuda_version }}
      run:
        - {{ pin_compatible("cuda-version", max_pin="x.x") }}
        - {{ pin_subpackage("cuda-nvtx", exact=True) }}  # [linux]
      run_constrained:
        - arm-variant * {{ arm_variant_type }}  # [aarch64]
    test:
      commands:
        - test -L $PREFIX/lib/libnvToolsExt.so                                                      # [linux]
        - test -f $PREFIX/lib/pkgconfig/nvToolsExt*.pc                                              # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/nvToolsExtCuda.h                        # [linux]
        - test -f $PREFIX/targets/{{ target_name }}/include/nvtx3/nvToolsExtCuda.h                  # [linux]
        - test -L $PREFIX/targets/{{ target_name }}/lib/libnvToolsExt.so                            # [linux]
        - if not exist %LIBRARY_INC%\targets\{{ target_name }}\nvtx3\nvToolsExt.h exit 1  # [win]
    about:
      home: https://developer.nvidia.com/cuda-toolkit
      license_file: LICENSE
      license: LicenseRef-NVIDIA-End-User-License-Agreement
      license_url: https://docs.nvidia.com/cuda/eula/index.html
      summary: A C-based API for annotating events, code ranges, and resources
      description: |
        A C-based API for annotating events, code ranges, and resources in your
        applications. Applications which integrate NVTX can use the Visual Profiler
        to capture and visualize these events and ranges.
      doc_url: https://docs.nvidia.com/nvtx/

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: A C-based API for annotating events, code ranges, and resources
  description: |
    A C-based API for annotating events, code ranges, and resources in your
    applications. Applications which integrate NVTX can use the Visual Profiler
    to capture and visualize these events and ranges.
  doc_url: https://docs.nvidia.com/nvtx/

extra:
  recipe-maintainers:
    - conda-forge/cuda
